version: '3'

volumes:
  bosch_db_data:
services:
  db:
    restart: always
    image: postgres:16
    container_name: bosch__service_db
    ports:
      - 54325:5432
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - bosch_db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: core
      POSTGRES_PASSWORD: password
      APP_DB_NAMES: '$DB_NAME'
      APP_DB_USER: $DB_USERNAME
      APP_DB_PASS: $DB_PASS
      APP_DB_SCHEMAS: $DB_SCHEMA
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5